language: node_js
node_js: node
env:
- ELM_VERSION=0.18.0 ELM_TEST=0.18.12
cache:
  directories:
  - elm-stuff/build-artifacts
  - elm-stuff/packages
  - tests/elm-stuff/build-artifacts
  - tests/elm-stuff/packages
  - sysconfcpus
  - "$HOME/.npm"
before_install:
- |
  if [ ! -d sysconfcpus/bin ];
  then
    git clone https://github.com/obmarg/libsysconfcpus.git;
    cd libsysconfcpus;
    ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
    make && make install;
    cd ..;
  fi
install:
- npm install -g elm@$ELM_VERSION elm-test@$ELM_TEST create-elm-app
- mv $(npm config get prefix)/bin/elm-make $(npm config get prefix)/bin/elm-make-old
- printf "#\041/bin/bash\n\necho \"Running elm-make with sysconfcpus -n 2\"\n\n$TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus
  -n 2 elm-make-old \"\$@\"" > $(npm config get prefix)/bin/elm-make
- chmod +x $(npm config get prefix)/bin/elm-make
- travis_retry elm package install --yes
- elm-app production
before_script:
  - mv /build /prodBuild
script:
- elm-test --verbose
deploy:
  provider: heroku
  api_key:
    secure: a9hOa0Y1jJ6vhVcXsGqH1NBHqBb4vGZTvB668uNKHXtTNhcHKd6QmXG85z17yuOHzh3VlxGP2XpiwHNxWJorncYXCpBkG/str4ns7jGZL7SB9ylUSVRMndYx9+ovxanEc2bDvRDeT+olCxO6C7Gb9ivjLJVUT7w+oPvOg2/9QrsdaR4fedJLcv9Rlo4YYkUsPO9diylhQVe8Jv0qKucU4+g6sirq7lYazR0Cd9O1LS44+mlGJsgaNyYGUXWvK3U2iHdHQAtZGbtFN8UG+w3c7vTKiob19t/N+C5IZXnq19aCIAapOX5+WfRuSpchpj9h/P8x2IFAqpnGmpSZhScw7Otdv1tvZ66vyk3nHiZjgkl6hs9xYx0OFUcBW6mwGkpUzqVN47rRl+32CWRqiG1V/HVMiqUoGXtJR3WvFVWDyIMUhmBJeJJilXEfqVAIKex2HuxLTcuxgQQkwQ4HCc02LquZh1WuKBcQERj4THKRJNNpQ7QUNzOGXWBZdvu0plRNxW1JMSCA3f3ADMbYN5iSnlwsJt8EgbNoMNAhJlqB30eUtmYitqMpKd0GK0KfEhdxWAmc6+ysioGbEBWDatRP95Lgk0kEpWL78ojxalAcT/xw+WMk5ZpPgF/0L+5rFE/0AS5SFSwX5e/XS7PsopDRSB9D35WiWeMGABsHV0BZq4A=
  app: elmapp
  skip_cleanup: true
